services:
  backend:
    build:
      context: ./potter_api
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - neo4j_network
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    networks:
      - neo4j_network
    ports:
      - "3000:5173"
    depends_on:
      - backend

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"  # веб-интерфейс (HTTP)
      - "7687:7687"  # протокол Bolt для подключения
    volumes:
      - neo4j_data:/data  # сохраняем данные
      - neo4j_logs:/logs  # сохраняем логи
    networks:
      - neo4j_network
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "${NEO4J_USER}", "-p", "${NEO4J_PASSWORD}", "RETURN 1"]
      interval: 5s
      retries: 3
      start_period: 10s

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  neo4j_network:
    driver: bridge
